### ISSUE TITLE
Buckets were not generated when you deploy a team with bitbucket

### ISSUE THREAD

**Issue by YuliemAlavez** [awslabs/aws-serverless-data-lake-framework#102]
When you create the foundational SDLF using:

./deploy.sh -s devops -r us-east-1 -f -x bbucket

The framework create the repositories in bitbucket and codecommit

Posteriorly when you create a team and push the code the deploy on bitbucket show that all looks good but the team repositories didn't create. 

I reviewed the code and in the file aws-serverless-data-lake-framework/thirdparty-scms/bbucket/bitbucket-team-pipelines.yml   in the step "Create repositories on bitbucket" the condition             

  if [[ "$OUTPUT" == *"not found"* ]]; then

Will be like these

if [[ "$OUTPUT" == *"no longer exists"* ]]; then

Because the variable OUTPUT have the message like these when the repository doesn't exist:  

{"type": "error", "error": {"message": "You may not have access to this repository or it no longer exists in this workspace. If you think this repository exists and you have access, make sure you are authenticated."}}

**Comment by cnfait** [comment]
Thank you for reporting this bug! the fix has now been merged in.
