### ISSUE TITLE
[Deploying the Foundations] sdlf-foundations-rS3Stack FAILS to create.

### ISSUE THREAD

**Issue by Druizm128** [awslabs/aws-serverless-data-lake-framework#137]
**Describe the bug**
Team, I have tried  **Deploying SDLF** section. There is a problem with the CloudFormation stack **sdlf-foundations-rS3Stack**. It says Embedded stack arn:aws:cloudformation:us-east-1:************:stack/sdlf-foundations-rS3Stack-1HIU1XN1M2Z6C/558b2930-edcf-11ed-9eb9-0e8bcc37f821 was not successfully created: The following resource(s) failed to create: [rStageBucketLakeFormationS3Registration, rAnalyticsBucketLakeFormationS3Registration, rRawBucketLakeFormationS3Registration, rDataQualityBucketLakeFormationS3Registration]. The only thing I have done is to follow the instructions in **Deploying the Foundations**. I have not changed the parameters.

**To Reproduce**
1. I follow the instructions in  **Deploying the Foundations**..

**Expected behavior**
I should be able to deploy it successfully.

**Screenshots**

<img width="1304" alt="Screenshot 2023-05-08 at 13 02 05" src="https://user-images.githubusercontent.com/6299564/236910881-a2ea65fb-761e-48f5-924d-032124c62a12.png">

<img width="1304" alt="Screenshot 2023-05-08 at 13 03 08" src="https://user-images.githubusercontent.com/6299564/236910959-99031153-ebd3-4d45-8c0d-a4b7d32c1079.png">

<img width="1572" alt="Screenshot 2023-05-08 at 13 03 54" src="https://user-images.githubusercontent.com/6299564/236911036-3900b3ba-3288-41dd-bc9c-27dbc3e6d744.png">

<img width="1561" alt="Screenshot 2023-05-08 at 13 06 21" src="https://user-images.githubusercontent.com/6299564/236911055-63e56bb1-0ecf-4938-8eb9-1cb779b60011.png">

**SDLF release (if known):**
Not sure, I deployed this on May 8th, 2023.

**Additional context**
I tried deploying in different accounts, and got the same result. In summary this bug has left the first part of the workshop useless. Let me know if I can be of more help.

**Comment by cnfait** [comment]
Thanks for raising this issue. This is due to a missing service role for Lake Formation data access, required when registering buckets in Lake Formation. The temporary fix is to manually register any bucket using the AWS console, to trigger the role creation, then rerun the workshop.

I've opened a PR with a better fix: #138 

Once it is merged in main, the issue should be gone.
