### ISSUE TITLE
What is the best, one bucket or multiple bucket?

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-serverless-data-lake-framework#15]
hello, how are you?

Based on your experience, which is the best option one bucket for all datalake zones or one bucket for each datalake zone?

For example, now my datalake has 3 zones

s3://bucket_name/landing
s3://bucket_name/raw
s3://bucket_name/refined

Now all zones are in the same bucket, but should I divide? My question is about performance and governance reasons.
With different buckets is a way to be sure if our zones are in different s3 partitions, is it make sense?

thank you.

**Comment by jaidisido** [comment]
Hi Ruben - that is a good question that many organizations ask when implementing a data lake. 

There are no specific guidance on the use of single or multi S3 Buckets strategies. We have seen a very large data lake implementation using a single S3 Bucket as well as implementations that leverage a multi-S3 Bucket strategy.

One benefit of the multiple S3 buckets configuration is the ability to have a different configuration (policies) for each bucket, that in turn are inherited by all objects residing in those buckets. For example, turning Versioning policy ON will protect all objects in the bucket against accidental overwrites and deletes. Once the policy is on, all objects and folders within the S3 Bucket will be impacted by the policy. With that in mind, it's common to have a strict policy on the RAW bucket for example while others are less restrictive and have wider usage.

Hope this helps

**Comment by rubenssoto** [comment]
Your point about data versioning is very very important. Do you have any point about performance? I talk to some Apple folks and they advise me to have different buckets is good for performance too, something related to s3 partition.

**Comment by jaidisido** [comment]
S3 partitioning is at a prefix level, so would be valid regardless of the number of buckets. Here is some documentation around that: https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html

**Comment by kocham** [comment]
Buckets can store an unlimited number of objects in a bucket without impacting performance. The objects can be stored in a single bucket or across multiple buckets----from aws doc
