### ISSUE TITLE
The GetCrawler step in  the sdlf-engineering-main-sm-b step function failed due to a lack of permission 

### ISSUE THREAD

**Issue by oleksapetrenko** [awslabs/aws-serverless-data-lake-framework#242]
The GetCrawler step in  the sdlf-engineering-main-sm-b step function failed due to a lack of permission 

User: arn:aws:sts::XXXXXXX:assumed-role/sdlf-engineering-pipeline-rMainBrStatesExecutionRol-RDG6yr1FUkJK/SVCYoZXhoIJzVtyCRCpayDZwRYlWEKHX is not authorized to perform: glue:GetCrawler on resource: arn:aws:glue:eu-west-1:XXXXXXX:crawler/sdlf-engineering-legislators-post-stage-crawler because no permissions boundary allows the glue:GetCrawler action (Service: Glue, Status Code: 400, Request ID: b2af6de6-463f-46e6-ad58-6214bdfeab34)

**Comment by oleksapetrenko** [comment]
This is a different one, it is about boundary limits, simply glue:GetCrawler action is not allowed

**Comment by cnfait** [comment]
I'm assuming this is fixed then, don't hesitate to add a comment if you still face it!

**Comment by oleksapetrenko** [comment]
Thanks, fixed
