### ISSUE TITLE
Update GitHub actions to the latest actions version

### ISSUE THREAD

**Issue by cnfait** [awslabs/aws-serverless-data-lake-framework#252]
**Describe the solution you'd like**
Update our [workflow](https://github.com/awslabs/aws-serverless-data-lake-framework/blob/main/.github/workflows/static-checking.yml) to use the latest version of the different GitHub actions (for example we use `actions/checkout@v3` when `v4` is available)

**Comment by fleventy-5** [comment]
@cnfait Can I work on this?

**Comment by cnfait** [comment]
done in #254, thank you @fleventy-5
