### ISSUE TITLE
sdlf-cicd-prerequisites failing

### ISSUE THREAD

**Issue by kangsoon93** [awslabs/aws-serverless-data-lake-framework#266]
**Describe the bug**
Creation of rCodePipelineFirstRunStopperLambdaLogGroup causes the stack to fail.

**To Reproduce**
1) Trigger codebuild project after running sdlf-workshop-deployment
2) sdlf-cicd-prerequisites stack is created

**Expected behavior**
Resource handler returned message: "User with accountId:XXX is not authorized to perform CreateLogGroup with Tags. An additional permission "logs:TagResource" is required. (Service: CloudWatchLogs, Status Code: 400, Request ID: dcc9e659-9636-4565-beed-0a726dcb8847)" (RequestToken: 9e25ac89-c581-4e98-4950-71e2612abbba, HandlerErrorCode:

**Screenshots**

**SDLF release (if known):**
V2.1

**Additional context**

**Comment by cnfait** [comment]
Thank you for raising the issue - I've just fixed it. I'm keeping the ticket open for now as I'm checking other things around this same permission.
