### ISSUE TITLE
iam:PassRole not allowed

### ISSUE THREAD

**Issue by kangsoon93** [awslabs/aws-serverless-data-lake-framework#275]
**Describe the bug**
When creating pipeline, iam:PassRole policy is not allowed.

**To Reproduce**
1. Under Deploying a Pipeline, commit to sdlf-main-{domain}-{team}

**Expected behavior**
API: cloudFormation User: arn:aws:sts::XXX:assumed-role/sdlf-cicd-team-engineering/AWSCloudFormation is not authorized to perform: iam:PassRole on resource: arn:aws:iam::XXX:role/sdlf-cicd-team-engineering because no identity-based policy allows the iam:PassRole action

**SDLF release (if known):**
v2.1

**Additional context**
The following is the inline policy under sdlf-cicd-team-engineering role causing the bug. cloudformation.amazonaws.com should be added to service under Condition, and resource ARN instead should be arn:aws:iam::XXX:role/sdlf-*

"Statement": [
		{
			"Condition": {
				"StringEquals": {
					"iam:PassedToService": [
						"lambda.amazonaws.com",
						"states.amazonaws.com",
						"glue.amazonaws.com"
					]
				}
			},
			"Action": [
				"iam:PassRole"
			],
			"Resource": [
				"arn:aws:iam::XXX:role/sdlf-dae/sdlf-*"
			],
			"Effect": "Allow"
		},

**Comment by cnfait** [comment]
https://github.com/awslabs/aws-serverless-data-lake-framework/commit/b92a2959128e120101103677071e308acc0ecb01

**Comment by kangsoon93** [comment]
Thanks, I modified my IAM role directly to add the policy change. However, when i re-triggered the codebuild step, the following error occured:

API: cloudFormation User: arn:aws:sts::XXX:assumed-role/sdlf-cicd-team-engineering/AWSCloudFormation is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:ap-southeast-1:XXX:stack/sdlf-{team}-pipelines-dev-rMain-U2WWY63VU1ZJ/* because no identity-based policy allows the cloudformation:CreateStack action

**Comment by cnfait** [comment]
Looking into it, thanks for raising the issue!

**Comment by cnfait** [comment]
added the permissions in https://github.com/awslabs/aws-serverless-data-lake-framework/commit/ca3a6f668254e22effd0920513263b80341a1c12
published a new micro version https://github.com/awslabs/aws-serverless-data-lake-framework/releases/tag/2.1.1
the workshop has been updated

it looks like there has been a change in the way nested stacks are created, it's a bit weird. I'm closing this issue as it's fixed but will investigate anyway.
