### ISSUE TITLE
Attaching AWS SDK for pandas layer to lambda via sdlf stage template.yaml fails

### ISSUE THREAD

**Issue by kangsoon-dev** [awslabs/aws-serverless-data-lake-framework#276]
**Describe the bug**
Resource handler returned message: "User: arn:aws:sts::XXX:assumed-role/sdlf-cicd-team-engineering/AWSCloudFormation is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:ap-southeast-1:336392948345:layer:AWSSDKPandas-Python311:8 because no identity-based policy allows the lambda:GetLayerVersion action.

**To Reproduce**
1. Under sdlf-stageA, edit template.yaml
2. Under Layers, add the arn of the AWS SDK for pandas layer version: arn:aws:lambda:ap-southeast-1:336392948345:layer:AWSSDKPandas-Python311:8
3. Trigger the sdlf-cicd-teams-datalake-dev-engineering-rTeamCodePipeline

**Expected behavior**
Nested CF stack that is updating resources for the stage fails:
Resource handler returned message: "User: arn:aws:sts::XXX:assumed-role/sdlf-cicd-team-engineering/AWSCloudFormation is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:ap-southeast-1:336392948345:layer:AWSSDKPandas-Python311:8 because no identity-based policy allows the lambda:GetLayerVersion action.

**SDLF release (if known):**
v2.1.1

**Comment by kangsoon-dev** [comment]
Please see the pull request for the fix.

**Comment by cnfait** [comment]
I'm reopening this ticket - we usually wait for the fix to be accepted/merged into main before closing issues!

**Comment by cnfait** [comment]
Fixed in https://github.com/awslabs/aws-serverless-data-lake-framework/pull/277
