### ISSUE TITLE
CloudFormation stack for custom stage creation failed

### ISSUE THREAD

**Issue by kangsoon-dev** [awslabs/aws-serverless-data-lake-framework#282]
**Describe the bug**
The CloudFormation stack that creates the custom stage using the CF module fails.

**To Reproduce**
1. Create a new repo on codecommit with name sdlf-{domain}-{team}-customStageA/customStageB
2. Clone stageA and stageB
3. Update remote on local repo to point to new CodeCommit repos and push to dev branch.
4. In sdlf-main-{domain)-(team) repo, update pipeline-main.yaml file to use the custom stages - Type: {domain}::{team}::customStageA::MODULE
5. Push sdlf-main-{domain)-(team) repo to CodeCommit
6. rTeamCodePipeline starts execution.
7. BuildStages creates CF stack but fails.

**Expected behavior**
Resource handler returned message: "Error validating schemaHandlerPackage. Check the permissions on the bucket and object in your account and try again. (Service: CloudFormation, Status Code: 400, Request ID: b596963d-ab80-40d3-a990-38e13b2aafb8)" (RequestToken: 8c881865-4364-ae12-4084-fabf6b1ec9f1, HandlerErrorCode: GeneralServiceException)

**SDLF release (if known):**
v2.1.1

**Comment by cnfait** [comment]
Fixed in https://github.com/awslabs/aws-serverless-data-lake-framework/pull/277
