### ISSUE TITLE
sdlf-pc-legislators-preupdate-A Lambda Function timing out

### ISSUE THREAD

**Issue by bfeliano** [awslabs/aws-serverless-data-lake-framework#329]
Hey team,

I have deployed SDLF in a cross-account strategy. All resources were deployed successfully, following the instructions in the Workshop.
However, when I upload the 4 files to the raw bucket, the Step Function A fails, because Lambda sdlf-pc-legislators-preupdate-A is timing out during `Initializing Octagon client `.

Step Function Error Message:
```json
{
  "cause": "The cause could not be determined because Lambda did not return an error type. Returned payload: {\"errorMessage\":\"2024-05-06T13:44:03.691Z 58439e2d-f6e2-4339-83ac-c8be91d1ea23 Task timed out after 300.01 seconds\"}",
  "error": "Lambda.Unknown",
  "resource": "invoke",
  "resourceType": "lambda"
}
```

Lambda log events
```
timestamp,message
1715002743340,"INIT_START Runtime Version: python:3.12.v25	Runtime Version ARN: arn:aws:lambda:eu-west-1::runtime:eb23ce52a7ad2bcf849de9f8cb1e3bae200e62ddb9e03883cc29d7c7a5eade03
"
1715002743676,"START RequestId: 58439e2d-f6e2-4339-83ac-c8be91d1ea23 Version: $LATEST
"
1715002743676,"[INFO]	2024-05-06T13:39:03.676Z	58439e2d-f6e2-4339-83ac-c8be91d1ea23	Fetching event data from previous step
"
1715002743676,"[INFO]	2024-05-06T13:39:03.676Z	58439e2d-f6e2-4339-83ac-c8be91d1ea23	Initializing Octagon client
"
1715003043692,"2024-05-06T13:44:03.691Z 58439e2d-f6e2-4339-83ac-c8be91d1ea23 Task timed out after 300.01 seconds

"
1715003043692,"END RequestId: 58439e2d-f6e2-4339-83ac-c8be91d1ea23
"
1715003043692,"REPORT RequestId: 58439e2d-f6e2-4339-83ac-c8be91d1ea23	Duration: 300011.97 ms	Billed Duration: 300000 ms	Memory Size: 128 MB	Max Memory Used: 76 MB	Init Duration: 333.73 ms	
"
1715003043744,"INIT_START Runtime Version: python:3.12.v25	Runtime Version ARN: arn:aws:lambda:eu-west-1::runtime:eb23ce52a7ad2bcf849de9f8cb1e3bae200e62ddb9e03883cc29d7c7a5eade03
"
```

From the [transformations ](https://catalog.us-east-1.prod.workshops.aws/workshops/501cb14c-91b3-455c-a2a9-d0a21ce68114/en-US/10-deployment/600-transformations) steps it is also mentioned the below:

![afbeelding](https://github.com/awslabs/aws-serverless-data-lake-framework/assets/78472054/a2eb807e-1874-48ae-8305-fad8b9e1112c)

However, my DynamoDB doesn't have any items inside the `octagon-Datasets-dev` Table.

Is there an easy way to find out why the Lambda is timing out, please?

Thanks,
Bruno

**Comment by cnfait** [comment]
Hey @bfeliano, can I assume you've been able to find the issue? do you need more help?

**Comment by bfeliano** [comment]
Hi Cyril,
Yes, there was an issue with our VPC. SDLF was successfully deployed after adjusting it.
Sorry for opening this.

Thanks,
Bruno
