### ISSUE TITLE
Ingest subset of tables by DMS

### ISSUE THREAD

**Issue by alt-victor** [awslabs/aws-serverless-data-lake-framework#36]
Is there a way to ingest multiple tables from a database without having to do it for all in it?

Also, using wildcards like "%" wouldn't be an option since the table names are completely different.

**Comment by jaidisido** [comment]
Hi @alt-victor, DMS tables ingestion is determined by specifying rules such as the schema or table names. The full list is available [here](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TableMapping.SelectionTransformation.Selections.html).

Once you have designed your rules, you can specify them directly in the DMS task [definition](https://github.com/awslabs/aws-serverless-data-lake-framework/blob/5bf3ae1a781a6f754d5ce7bd95672ee77edac7cd/sdlf-utils/ingestion-examples/cdc/dms-task/template.yaml#L137)

**Comment by alt-victor** [comment]
Yes. And in the same documentation page it shows that I would need to create a second "rule" object, with another "object-locator" object, with the "table-name" parameter specifing with the other table name.

My question is how do I do that with the parameters-${ENV}.json

P.S.: Sorry for not being specific in my question.

**Comment by andrewlacy** [comment]
Add something like the following to your table_mappings.json...  

                {
                        "rule-type": "selection",
                        "rule-id": "5",
                        "rule-name": "Selection Rule OTESTUSER",
                        "object-locator": {
                                "schema-name": "OTESTUSER",
                                "table-name": "%"
                        },
                        "rule-action": "include",
                        "filters": []
                }

**Comment by jaidisido** [comment]
You would indeed need to update the [definition](https://github.com/awslabs/aws-serverless-data-lake-framework/blob/5bf3ae1a781a6f754d5ce7bd95672ee77edac7cd/sdlf-utils/ingestion-examples/cdc/dms-task/template.yaml#L137) to add a second JSON in the array. You would also need to update the Parameters section of the template to reference two variables (e.g. table1 and table2). CloudFormation is not dynamic enough to handle splitting list or anything of the kind
