### ISSUE TITLE
Stack deployment fails - role sdlf-cicd-codebuild policy exceeds maximum 10240 bytes

### ISSUE THREAD

**Issue by bencaldwell** [awslabs/aws-serverless-data-lake-framework#61]
**Describe the bug**
When following the workshop to setup SDLF I receive an error on deployment of the stack _sdlf-cicd-child-foundations_

**To Reproduce**
1. Create a new account and change region to _ap-southeast-2_
2. Deploy the stack at https://console.aws.amazon.com/cloudformation/home?#/stacks/new?stackName=sdlf-workshop-deployment&templateURL=https://sdlf-os-public-artifacts.s3-us-west-2.amazonaws.com/deploying-foundations/template.yaml
3. After some time the _self-cicd-child-foundations_ stack will move to state _ROLLBACK_FAILED_

**Expected behavior**
The stack should successfully deploy.

**Comment by bencaldwell** [comment]
I have deployed the stack in _us-east-1_ and can confirm that it works for me there. How do we get this working in _ap-southeast-2_? Is this just a case of an extra 5 characters in the region name tipping the policy size over the edge?

**Comment by jaidisido** [comment]
Thanks for raising this @bencaldwell, you are right - it looks like the extra character in the Sydney region are enough to cause the error. I have reduced the policy size and it should now be fixed.

**Comment by bencaldwell** [comment]
I have confirmed that this deploys in ap-southeast-2 now. Thanks for the prompt fix!
