### ISSUE TITLE
Error Foundational Initial Setup

### ISSUE THREAD

**Issue by davidsilvaroot** [awslabs/aws-serverless-data-lake-framework#73]
**Describe the bug**
When I did initial setup from this link: https://console.aws.amazon.com/cloudformation/home?#/stacks/new?stackName=sdlf-workshop-deployment&templateURL=https://sdlf-os-public-artifacts.s3-us-west-2.amazonaws.com/deploying-foundations/template.yaml, I can't create foundational cloudformation stack.

**To Reproduce**
1. Go to button 'Launch stack'. Link: https://catalog.us-east-1.prod.workshops.aws/workshops/501cb14c-91b3-455c-a2a9-d0a21ce68114/en-US/10-deployment/100-setup
2. Wait to stack finish
3. Click on stack name "sdlf-workshop-deployment"
4. See error on tab "Events"
5. Go to Logical ID: "rCustomLambdaTrigger"
6. See error: `Received response status [FAILED] from custom resource. Message returned: CloudWatch Log Stream: 2022/08/05/[$LATEST]bf75ac9ecd1b4dec88661922c049xxxx (RequestId: 3a8b44b7-9f43-45e8-9c7a-5d8995b3fxxxx)`
7. Cloudwatch log is:
`[ERROR] AccountLimitExceededException: An error occurred (AccountLimitExceededException) when calling the StartBuild operation: Cannot have more than 0 builds in queue for the account
Traceback (most recent call last):
  File "/var/task/index.py", line 49, in lambda_handler
    raise e
  File "/var/task/index.py", line 33, in lambda_handler
    cb.start_build(projectName=CODE_BUILD_PROJECT)
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
`

**Expected behavior**
I expected to see stacks implementing the SDLF CICD are provisioned in CloudFormation:
- sdlf-cicd-child-foundations
- sdlf-cicd-shared-foundations-dev
- sdlf-cicd-team-repos

and Git repositories into CodeCommit

**Screenshots**
Cloudformation
![image](https://user-images.githubusercontent.com/20761454/183205145-97b23df8-57d5-4699-b1a0-9c21e065c851.png)

Cloudwatch
![image](https://user-images.githubusercontent.com/20761454/183207779-53659371-d634-4c4e-aea5-97329e1651e3.png)

**SDLF release (if known):**
Last version of workshop

**Additional context**
To launch this stack I used an IAM Administrator account

**Comment by jaidisido** [comment]
@davidsilvaroot as the error indicates (`[ERROR] AccountLimitExceededException: An error occurred (AccountLimitExceededException) when calling the StartBuild operation: Cannot have more than 0 builds in queue`), there is an account limit on the CodeBuild service in your AWS account, meaning you are not able to start CodeBuild projects at the moment. You would have to raise that limit first.

**Comment by davidsilvaroot** [comment]
Hello @jaidisido , I check my quota service and I saw values by default are:

![image](https://user-images.githubusercontent.com/20761454/183259108-81ecf52a-5141-44a2-9617-b2ccd0e23c2d.png)

The values are fine, maybe it's another AWS problem.

**Comment by davidsilvaroot** [comment]
My quota was in 60, so I requested on aws support to increase to 61 and then it's worked, for some reason that value on screenshot is bad and isn't correct.
